---
abstract: 'Run commands simply, with detailed diagnostics'
author:
  - 'Paul Fenwick <pjf@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  Test: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IPC-System-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '0'
  List::Util: '0'
  POSIX: '0'
  Scalar::Util: '0'
  constant: '0'
  perl: '5.006'
  re: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/pjf/ipc-system-simple/issues
  homepage: http://thenceforward.net/perl/modules/IPC-System-Simple/
  repository: https://github.com/pjf/ipc-system-simple.git
version: '1.30'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
